# Generated by Django 4.0 on 2022-01-27 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Vapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='adding_hospitals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hospital_name', models.CharField(max_length=20)),
                ('H_details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='nurse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('Email', models.CharField(max_length=20)),
                ('contact_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reportcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.CharField(max_length=20)),
                ('vaccine', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('start_time', models.CharField(max_length=20)),
                ('end_time', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Address', models.TextField()),
                ('contact_no', models.IntegerField()),
                ('Child_name', models.CharField(max_length=20)),
                ('child_age', models.IntegerField()),
                ('child_gender', models.CharField(max_length=20)),
                ('Recent_vaccination', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='vaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_name', models.CharField(max_length=20)),
                ('vaccine_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='U_Complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detils', models.TextField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='N_Complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detils', models.TextField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vapp.nurse')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('vaccine_name', models.CharField(max_length=20)),
                ('vaccinated', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vapp.schedule')),
            ],
        ),
    ]
