# Generated by Django 4.0 on 2022-03-09 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment_details',
            name='vaccinated',
            field=models.BooleanField(default=False),
        ),
    ]
