# Generated by Django 4.0.3 on 2022-05-02 02:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Vapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint_details',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
