# Generated by Django 4.0 on 2022-03-09 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vapp', '0002_appointment_details_vaccinated'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccine',
            name='approval_status',
            field=models.IntegerField(default=0),
        ),
    ]
