# Generated by Django 4.0 on 2022-02-07 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vapp', '0002_alter_complaint_date_alter_complaint_reply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='user',
            new_name='user_name',
        ),
    ]
