# Generated by Django 4.0 on 2022-02-07 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vapp', '0003_rename_user_complaint_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='user_name',
            new_name='user',
        ),
    ]
