# Generated by Django 4.0 on 2022-01-28 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Vapp', '0003_hospital_nurse_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='nurse',
            name='hos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Vapp.hospital'),
        ),
    ]
