# Generated by Django 4.0 on 2022-02-02 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vapp', '0004_nurse_hos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nurse',
            old_name='hos',
            new_name='Hospital_name',
        ),
    ]
