# Generated by Django 4.0 on 2022-02-04 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vapp', '0005_rename_hos_nurse_hospital_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='nurse',
            new_name='Nurses',
        ),
    ]
