# Generated by Django 4.0 on 2022-02-09 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vapp', '0006_delete_complaint'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
