# Generated by Django 4.0 on 2022-02-04 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vapp', '0006_rename_nurse_nurses'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Nurses',
            new_name='nurse',
        ),
    ]
