# Generated by Django 4.0 on 2022-02-04 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vapp', '0007_rename_nurses_nurse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='contact',
        ),
        migrations.AddField(
            model_name='hospital',
            name='contact_no',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hospital',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='place',
            field=models.CharField(max_length=50),
        ),
    ]
