# Generated by Django 4.0 on 2022-02-09 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vapp', '0008_complaint_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='user',
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='Complaint',
        ),
    ]
