# Generated by Django 4.0 on 2022-02-05 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Vapp', '0009_remove_reportcard_patient_reportcard_patient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='u_complaints',
            name='person',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='schedule',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vapp.user'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='vaccine_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vapp.vaccine'),
        ),
        migrations.DeleteModel(
            name='N_Complaints',
        ),
        migrations.DeleteModel(
            name='U_Complaints',
        ),
    ]
