# Generated by Django 4.0 on 2022-02-06 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Vapp', '0010_remove_u_complaints_person_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('complaint', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('reply', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vapp.user')),
            ],
        ),
        migrations.DeleteModel(
            name='adding_hospitals',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='end_time',
            field=models.TimeField(max_length=20),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_time',
            field=models.TimeField(max_length=20),
        ),
    ]
