# Generated by Django 4.0 on 2022-02-09 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vapp', '0010_complaint_details_appointment_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint_details',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
